spring:
  datasource:
    url: jdbc:h2:mem:pedidosdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # o create para pruebas
    show-sql: true
  h2:
    console:
      enabled: true